### ISSUE TITLE
iOS doesn't compile

### ISSUE THREAD

**Issue by jaumard** [saibotma/jitsi_meet_wrapper#10]
I have followed the step on readme but getting this error where trying to run the app:
```
 Command CompileSwiftSources failed with a nonzero exit code
    /Users/jaumard/.pub-cache/hosted/pub.dartlang.org/jitsi_meet_wrapper-0.0.1/ios/Classes/CustomPiPViewCoordinator.swift:64:69: warning: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes
                    let parentView = parentView ?? UIApplication.shared.keyWindow
                                                                        ^
    /Users/jaumard/.pub-cache/hosted/pub.dartlang.org/jitsi_meet_wrapper-0.0.1/ios/Classes/CustomPiPViewCoordinator.swift:165:33: error: cannot find 'PiPViewCoordinator' in scope
                    in: Bundle(for: PiPViewCoordinator.self),
                                    ^~~~~~~~~~~~~~~~~~
```

**Comment by saibotma** [comment]
As explained in the readme it currently does not compile for iOS simulator with Flutter lower than  2.8. Please upgrade your Flutter.

**Comment by jaumard** [comment]
Sorry I didn't read the bottom of the readme :D just the Android/iOS part :) 
Can't update for now as there is a regression in flutter web but I keep that in mind. I can launch on the simulator and flutter 2.5 by using Xcode so it's fine for now. 

I was wondering if you are considering bringing back the web version? Really would like to have it included in my website instead of launching another tab.

**Comment by saibotma** [comment]
Bringing back the web version is not planned yet and I have no time for it atm. PRs are welcomed. Feel free to create an issue.

**Comment by jaumard** [comment]
Hey @saibotma I'm back with that issue, I've update to the last flutter stable but still can't compile on iOS Simulator. Is there any settings to change in order to compile? I don't care it doesn't work on simulator but I would like at least be able to deploy and test my app without meetings.
