### ISSUE TITLE
app crashes when start meeting

### ISSUE THREAD

**Issue by Zidoun-Abdou** [saibotma/jitsi_meet_wrapper#101]

**Comment by Zidoun-Abdou** [comment]
you have to copy all the files from the example provided by the author located in example/android/app/src/main/res/ to your project your_project/android/app/src/main/res/

**Comment by AlexMP-Dev** [comment]
hello, the image asset button does not appear in android studio, any other solution? Or could you tell me what goes inside the folders?

**Comment by Zidoun-Abdou** [comment]
hy, there no need to find any asset button, you need to copy all the files located in : https://github.com/saibotma/jitsi_meet_wrapper/tree/main/jitsi_meet_wrapper/example/android/app/src/main/res
to your project : your_project/android/app/src/main/res/
