### ISSUE TITLE
How do I close the jitsi view (or call the end call function to close the jitsi view) programmitically?

### ISSUE THREAD

**Issue by isaanyoha** [saibotma/jitsi_meet_wrapper#110]
How do I close the jitsi view (or call the end call function to close the jitsi view) programmitically?

Navigator.of(context).pop(); closes the main app's current page (not jitsi view), while SystemNavigator.pop() quits the main app. Again, JitsiMeet.closeMeeting() does not close the view either, just the meeting process alone

How do I do this, please. Thank you!

**Comment by saibotma** [comment]
Did you already try calling `hangUp`?

**Comment by isaanyoha** [comment]
Yeah!!! I works now. Thank you!
