### ISSUE TITLE
FeatureFlagEnum how to add feature flag enum?

### ISSUE THREAD

**Issue by bagusandrewijaya** [saibotma/jitsi_meet_wrapper#114]
i cant add featureFlags in this dependency
    Map<FeatureFlagEnum, bool> featureFlags = {
      FeatureFlagEnum.WELCOME_PAGE_ENABLED: false,
    };

**Comment by saibotma** [comment]
Please read the [changlog](https://pub.dev/packages/jitsi_meet_wrapper/changelog#020).
