### ISSUE TITLE
Release build crashes when using package

### ISSUE THREAD

**Issue by Souljeee** [saibotma/jitsi_meet_wrapper#121]
During the android build of the release version, the application crashes with the following error:
![image](https://github.com/saibotma/jitsi_meet_wrapper/assets/69972824/f5dfe4a4-b743-40f4-86ba-d4a14eca2fbd)
Assembly takes place in the gitlab pipeline with Android Studio 2021.1.1.21
Gradle version - 7.4

**Comment by shabanov-krl** [comment]
same issue

it used to work, no updates were made and an error appeared one day

**Comment by shabanov-krl** [comment]
@saibotma i found this bugfix, maybe it's decision 

https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#common

**Comment by manh1707** [comment]
![image](https://github.com/saibotma/jitsi_meet_wrapper/assets/90319470/dfbffb35-0a5b-4641-a585-b5437d939dd0)
Did you add Proguard rule to your android.Here is the Proguard rule for android, add this and check release build again : 
https://github.com/jitsi/jitsi-meet/blob/master/android/app/proguard-rules.pro

**Comment by shabanov-krl** [comment]
> ![image](https://user-images.githubusercontent.com/90319470/264226994-dfbffb35-0a5b-4641-a585-b5437d939dd0.png) Did you add Proguard rule to your android.If missing, you must add Proguard-rules and check release build again. Check this Proguard rules : https://github.com/jitsi/jitsi-meet/blob/master/android/app/proguard-rules.pro

yes, we have this rules

**Comment by shabanov-krl** [comment]
@manh1707 for reproduce this bug, clean gradle cache, if you have done builds before, and run build again

it is necessary, because gradle cached jitsi and error occurs when loading it

**Comment by shabanov-krl** [comment]
the problem was in the vpn :point_right: :point_left:
