### ISSUE TITLE
User who created meet goes to lobby

### ISSUE THREAD

**Issue by DP-NOTHING** [saibotma/jitsi_meet_wrapper#125]
if user initially creates a meeting ,user is being redirected to lobby even if he is the one who first created the meeting. and it say you will join the meeting as soon as someone accepts your request and asks for password.
turning off lobby , turning off password , or turning off security is not working.

![Screenshot 2023-09-16 204410](https://github.com/saibotma/jitsi_meet_wrapper/assets/107257619/f9062b60-f3f6-4edf-8aeb-eb13ac77860b)

**Comment by Hiresh007** [comment]
yes i am also facing same problem in flutter

**Comment by khizar1556** [comment]
@DP-NOTHING i can fix that

**Comment by MihirPatel1432** [comment]
> @DP-NOTHING i can fix that

Can you please share solution

**Comment by DP-NOTHING** [comment]
solution :

if you don't provide server url then it will use jitsi default server meet.jit.si which require login to be moderator . now there are some community run servers jitsi.github.io/handbook/docs/community/community-instances

which doesn't require login to be moderator . just add serverurl in jitsi configuration with one of the community servers and it will run fine

**Comment by khizar1556** [comment]
> @MihirPatel1432 solution : if you don't provide server url then it will use jitsi default server meet.jit.si which require login to be moderator . now there are some community run servers jitsi.github.io/handbook/docs/community/community-instances
> 
> which doesn't require login to be moderator . just add serverurl in jitsi configuration with one of the community servers and it will run fine

yes this is the exact answer
