### ISSUE TITLE
upgrade sdk 

### ISSUE THREAD

**Issue by jaish702** [saibotma/jitsi_meet_wrapper#13]
plz upgrade your sdk from 4.0.0 to 4.1.0 in jitsi. and plz add background notifyer that notify the meeting is running in background. plz sir plzzzz

**Comment by saibotma** [comment]
Will upgrade eventually. Can you please create another issue for the background notifier.

**Comment by jaish702** [comment]
> Ok I will but plz ones again I am saying plz sir upgrade the SDK from 4.0.0 to 4.1.0.

**Comment by jagadish-pattanaik** [comment]
@saibotma can u let me know what all new features are there now after you have upgraded the SDK version in the old jitsi-meet repo?

**Comment by saibotma** [comment]
I am sorry, but I don't understand your question. And please open another issue if it does not have to do with this one.

**Comment by jaish702** [comment]
This are the all FeatureFlag with new one's :-
class FeatureFlagHelper {
  static Map<FeatureFlagEnum, String> featureFlags = {
    FeatureFlagEnum.ADD_PEOPLE_ENABLED: 'add-people.enabled',
    FeatureFlagEnum.AUDIO_FOCUS_DISABLED: 'audio-focus.disabled',
    FeatureFlagEnum.ANDROID_AUDIO_FOCUS_DISABLED:
        'android.audio-focus.disabled',
    FeatureFlagEnum.AUDIO_MUTE_BUTTON_ENABLED: 'audio-mute.enabled',
    FeatureFlagEnum.AUDIO_ONLY_BUTTON_ENABLED: 'audio-only.enabled',
    FeatureFlagEnum.CALENDAR_ENABLED: 'calendar.enabled',
    FeatureFlagEnum.CALL_INTEGRATION_ENABLED: 'call-integration.enabled',
    FeatureFlagEnum.CLOSE_CAPTIONS_ENABLED: 'close-captions.enabled',
    FeatureFlagEnum.CONFERENCE_TIMER_ENABLED: 'conference-timer.enabled',
    FeatureFlagEnum.CHAT_ENABLED: 'chat.enabled',
    FeatureFlagEnum.FILMSTRIP_ENABLED: 'filmstrip.enabled',
    FeatureFlagEnum.FULLSCREEN_ENABLED: 'fullscreen.enabled',
    FeatureFlagEnum.HELP_BUTTON_ENABLED: 'help.enabled',
    FeatureFlagEnum.INVITE_ENABLED: 'invite.enabled',
    FeatureFlagEnum.IOS_RECORDING_ENABLED: 'ios.recording.enabled',
    FeatureFlagEnum.IOS_SCREENSHARING_ENABLED: 'ios.screensharing.enabled',
    FeatureFlagEnum.ANDROID_SCREENSHARING_ENABLED:
        'android.screensharing.enabled',
    FeatureFlagEnum.SPEAKERSTATS_ENABLED: 'speakerstats.enabled',
    FeatureFlagEnum.KICK_OUT_ENABLED: 'kick-out.enabled',
    FeatureFlagEnum.LIVE_STREAMING_ENABLED: 'live-streaming.enabled',
    FeatureFlagEnum.LOBBY_MODE_ENABLED: 'lobby-mode.enabled',
    FeatureFlagEnum.MEETING_NAME_ENABLED: 'meeting-name.enabled',
    FeatureFlagEnum.MEETING_PASSWORD_ENABLED: 'meeting-password.enabled',
    FeatureFlagEnum.NOTIFICATIONS_ENABLED: 'notifications.enabled',
    FeatureFlagEnum.OVERFLOW_MENU_ENABLED: 'overflow-menu.enabled',
    FeatureFlagEnum.PIP_ENABLED: 'pip.enabled',
    FeatureFlagEnum.RAISE_HAND_ENABLED: 'raise-hand.enabled',
    FeatureFlagEnum.REACTIONS_ENABLED: 'reactions.enabled',
    FeatureFlagEnum.RECORDING_ENABLED: 'recording.enabled',
    FeatureFlagEnum.REPLACE_PARTICIPANT: 'replace.participant',
    FeatureFlagEnum.RESOLUTION: 'resolution',
    FeatureFlagEnum.SECURITY_OPTIONS_ENABLED: 'security-options.enabled',
    FeatureFlagEnum.SERVER_URL_CHANGE_ENABLED: 'server-url-change.enabled',
    FeatureFlagEnum.TILE_VIEW_ENABLED: 'tile-view.enabled',
    FeatureFlagEnum.TOOLBOX_ALWAYS_VISIBLE: 'toolbox.alwaysVisible',
    FeatureFlagEnum.TOOLBOX_ENABLED: 'toolbox.enabled',
    FeatureFlagEnum.VIDEO_MUTE_BUTTON_ENABLED: 'video-mute.enabled',
    FeatureFlagEnum.VIDEO_SHARE_BUTTON_ENABLED: 'video-share.enabled',
    FeatureFlagEnum.WELCOME_PAGE_ENABLED: 'welcomepage.enabled',
  };
}

**Comment by jaish702** [comment]
4.1.0 (2021-12-14)
Android
iOS
Changes
Created SecurityOptions React Navigation screen
Fixed issue where last participant is shown as inactive when the self view is hidden
Fixed not rendering display names in breakout-rooms
Adjust the timeout for unmute blocked notifications
Fixed the issue where the user muted by focus is able to unmute themselves even when the sender limit has been reached
Fixed chat and polls title
Re-enables PIP after stopping screen-share
Updated translations

Android
Fixed keyboard covering input on chat
Fixed NoClassDefFoundError for Android L/graphics/ColorSpace
Full changelog
iOS
N/A
Full changelog


and


 this is the link you can see all the changes :- 
https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

**Comment by jagadish-pattanaik** [comment]
That's great...I am trying to change only the SDK version and other versions to the latest in the old jitsi-meet repo from where this repo was created. Still am not that sure the feature flags will work...is there anything I need to do extra ot only version changing would work?

**Comment by jaish702** [comment]
> That's great...I am trying to change only the SDK version and other versions to the latest in the old jitsi-meet repo from where this repo was created. Still am not that sure the feature flags will work...is there anything I need to do extra or only version changing would work?

ANS:- No JUST  Change only the SDK version.

**Comment by jaish702** [comment]
hello I just want to remind you that you have not updated the SDK version till now.

**Comment by saibotma** [comment]
Available in version `0.0.2`.
