### ISSUE TITLE
Can we host jitsi at our own server like cloud hostinger or through firebase, please provide guidance and video on this.

### ISSUE THREAD

**Issue by vlibraryeducation** [saibotma/jitsi_meet_wrapper#132]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saibotma** [comment]
Yes you can. Please have a look at the [official Jitsi documentation](https://jitsi.github.io/handbook/docs/devops-guide/) for more information.
