### ISSUE TITLE
End Meeting Programmatically

### ISSUE THREAD

**Issue by zionnite** [saibotma/jitsi_meet_wrapper#25]
Hello sir,
thanks for all u do!

please sir, how do I end a meeting programmatically?

i really need this

**Comment by zionnite** [comment]
Is this do able?
@saibotma

**Comment by saibotma** [comment]
Hi there, yes it is doable with the official SDKs, however this first needs to be implemented in `jitsi_meet_wrapper`. Implementing it requires some more thorough thoughts, and unfortunately I don't have time the next days. I will however take a look at it as soon as I can.

**Comment by efraespada** [comment]
@zionnite I've opened a PR https://github.com/saibotma/jitsi_meet_wrapper/pull/34 for including this feature.

```dart
 JitsiMeetWrapper.closeMeeting();
```

You can use my fork while the PR is managed.

Clone the repo:

```bash
gh repo clone efraespada/jitsi_meet_wrapper
```

Use it locally:
```yml
jitsi_meet_wrapper:                           # android   ios
      path: ../jitsi_meet_wrapper/jitsi_meet_wrapper
```

**Comment by zionnite** [comment]
> @zionnite I've opened a PR https://github.com/saibotma/jitsi_meet_wrapper/pull/34 for including this feature.
> 
> ```dart
>  JitsiMeetWrapper.closeMeeting();
> ```
> 
> You can use my fork while the PR is managed.
> 
> Clone the repo:
> 
> ```bash
> gh repo clone efraespada/jitsi_meet_wrapper
> ```
> 
> Use it locally:
> ```yml
> jitsi_meet_wrapper:                           # android   ios
>       path: ../jitsi_meet_wrapper/jitsi_meet_wrapper
> ```

U are a life saver,
I will try it out and give u report asap

**Comment by zionnite** [comment]
okay, it was my mistake.

i had to read your instruction again and I had to do it like this

 ```
jitsi_meet_wrapper:
      path: /Users/apple/jitsi_meet_wrapper/jitsi_meet_wrapper
```
I did just this once and there was error, so when I added the below line, it was resolved

  ```
jitsi_meet_wrapper_platform_interface:
      path: /Users/apple/jitsi_meet_wrapper/jitsi_meet_wrapper_platform_interface
```

**Comment by duc1205** [comment]
Hi every one, i i have an event, i listen to the event and i make a call `JitsiMeetWrapper.closeMeeting()` but I don't want it to interfere when I press end call in the conversation then what should i do? @saibotma

**Comment by saibotma** [comment]
@duc1205 I am sorry, but I think I don't understand your question. Please create a new issue as it seems like this is a rather different issue than this one.

**Comment by duc1205** [comment]
> @duc1205 I am sorry, but I think I don't understand your question. Please create a new issue, as it seems like this is a rather different issue than this one.

i'm resolved, tks!!
