### ISSUE TITLE
Why is `pubspec.lock` included in git?

### ISSUE THREAD

**Issue by nilsreichardt** [saibotma/jitsi_meet_wrapper#27]
https://github.com/saibotma/jitsi_meet_wrapper/blob/6d7a0b12dcf48119ba2b39bc4bf2ea3b6f979833/.gitignore#L29

`pubspec.lock` is already in `.gitignore`, also with the reason why we should not commit it for library packages (👍) - is there a reason why `pubspec.lock` is out-comment?

**Comment by saibotma** [comment]
Thanks for the hint. Did not know this fact. Will be removed in 0.0.5.

**Comment by nilsreichardt** [comment]
Thanks ❤️
