### ISSUE TITLE
Install Jitsi on Android 12 not working

### ISSUE THREAD

**Issue by weconnectchat** [saibotma/jitsi_meet_wrapper#39]
Hi All, I see this issue is common, can someone please confirm if the Jitsi build on flutter can be installed on Android v12, and how to achieve that. 
Already added the android:exported="true" in AndroidManifest but cant install on version 12, shows issue " there was a problem parsing the package".

Thanks

**Comment by saibotma** [comment]
Please try the newest version of this package.
