### ISSUE TITLE
App crashing when clicking on  "participants".

### ISSUE THREAD

**Issue by msharibahmed** [saibotma/jitsi_meet_wrapper#41]
First, the screen becomes black but the video camera is still on. When clicking on "close app"(ANR pop-up) the camera stops working.

**Comment by Eng-NUREDDIN** [comment]
same issue for me, also when you open chat.

**Comment by Eng-NUREDDIN** [comment]
@msharibahmed could you able to solve the problem?

**Comment by msharibahmed** [comment]
@Eng-NUREDDIN 
 Yes. I used the jitsi_meet package and downgraded the Jitsi SDK to 4.1.0.
Also then fixed the theme name issue in the android manifiest.
That worked for me.

**Comment by chidera-ugonwa** [comment]
facing the same issue, is there any solution to this yet?

just switched to jitsi_meet_wrapper because the jitsi meet has too many compatibility issues with my project

**Comment by msharibahmed** [comment]
@chidera-ugonwa  I forked the jisti_meet plugin and fixed all the issues.
I will push the code on GitHub and attach the link to my repository here.

**Comment by chidera-ugonwa** [comment]
@msharibahmed Okay great! Thanks ):

**Comment by Eng-NUREDDIN** [comment]
use this i forked the repo and solve all the issue.
jitsi_meet:
    git:
      url: https://github.com/Eng-NUREDDIN/jitsi_meet.git
      path: jitsi_meet/
      ref: master

**Comment by chidera-ugonwa** [comment]
@Eng-NUREDDIN please i'm using your package but i'm still getting the type mismatch error "Inferred type is Activity? but expected Activity.

**Comment by chidera-ugonwa** [comment]
I've solved this problem.

in your app level build.gradle just add

implementation ("androidx.appcompat:appcompat:1.3.1") {
    version {
        strictly '1.3.1'
    }
}

works like a charm!

**Comment by saibotma** [comment]
Please try again with the newest version.
