### ISSUE TITLE
FeatureFlag.isToolboxEnabled does not work

### ISSUE THREAD

**Issue by abishop-jac** [saibotma/jitsi_meet_wrapper#44]
Looks like it is being (incorrectly) mapped to `toolbox.alwaysVisible` instead of `toolbox.enabled` (`jitsi_meet_wrapper_platform_interface/lib/method_channel_jitsi_meet_wrapper.dart` line 203)

**Comment by saibotma** [comment]
Is already in master and will be included in the next version.
