### ISSUE TITLE
Video and audio mute showing.

### ISSUE THREAD

**Issue by AmarpreetSingh18** [saibotma/jitsi_meet_wrapper#47]
Hi ,
I am using flutter app.I am connecting from mobile and desktop web browser.Having problem since few days,Video and audio mute showing .Actually the video and audio is on by the user.

<img width="317" alt="Screenshot 2022-07-29 at 12 25 27 AM" src="https://user-images.githubusercontent.com/23114692/181616102-0637e1e4-046b-4c0e-8e4c-9bdcdbdfb595.png">

Mobile video not displaying in browser but browser video showing in mobile.
please tell the solution

**Comment by saibotma** [comment]
Will update the jitsi meet SDK version in the next release. This will probably fix the issue.

**Comment by saibotma** [comment]
I close this issue for now. Please test if this issue still appears with the newest release.
