### ISSUE TITLE
app exited when tap on disabled icons (chat,audio ...etc)

### ISSUE THREAD

**Issue by omar-hadek** [saibotma/jitsi_meet_wrapper#48]

**Comment by Nabinda** [comment]
I am facing same is there any solution to it or can I disable/hide those buttons which causes app crash

**Comment by saibotma** [comment]
Probably have to upgrade to new jitsi meet sdk version. (#50)

**Comment by omar-hadek** [comment]
> Probably have to upgrade to new jitsi meet sdk version. (#50)

**Comment by omar-hadek** [comment]
> Probably have to upgrade to new jitsi meet sdk version. (#50)

i have already upgraded to the latest version 
some problems are occurred on the official package in production mode that's why i decided to use jitsi_meet_wrapper it works fine except that bug
