### ISSUE TITLE
Support web and flags

### ISSUE THREAD

**Issue by thorito** [saibotma/jitsi_meet_wrapper#55]
Excellent work !!

It would be better if:
1. Web support as in jitsi_meet 4.0.0
2. Add flags: 'speaker statistics', 'car mode', 'participating' and 'statistics of the participants'

Reference: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.ts

Thank you very much for your help

**Comment by saibotma** [comment]
Can you please create separate issues for the two bullet points? Thanks!
