### ISSUE TITLE
Your app uses a bad version of WebRTC, which contains security vulnerabilities.

### ISSUE THREAD

**Issue by rvharjinderbains** [saibotma/jitsi_meet_wrapper#57]
I have integrated jitsi_meet_wrapper plugin in my project and published app on google play store. I got below mentioned error message from google :-

"Your app uses a bad version of WebRTC, which contains security vulnerabilities."

I am using :-
Flutter : 2.10.5
Dart: 2.16.2
jitsi_meet_wrapper: ^0.0.1
callkeep :0.3.2
.....

Please provide me the solution

Thank you

**Comment by rvharjinderbains** [comment]
@saibotma any update regarding this issue???

**Comment by rvharjinderbains** [comment]
@nilsreichardt @abishop-jac @saibotma Have you checked this issue??

**Comment by rvharjinderbains** [comment]
@saibotma I am not getting any answer from your side. Can you update your library according to latest Webrtc?

I have also raised same issue in this group conversations:- https://groups.google.com/g/discuss-webrtc/c/HzfUFGYono8/m/JUj6jP5TAgAJ?utm_medium=email&utm_source=footer

**Comment by nilsreichardt** [comment]
Hi @rvharjinderbains, I'm sorry but I can't help because I'm not the maintainer of the package.

**Comment by rvharjinderbains** [comment]
It's ok @saibotma . Could you please let me know who is the maintainer of this package?

**Comment by saibotma** [comment]
@rvharjinderbains I am sorry that there is currently no progress. This is because we are very limited on time atm.
I will do my best to resolve this issue as soon as possible.

**Comment by mikegapinski** [comment]
@saibotma I fixed this issue by updating the Jitsi SDK version in our fork, the newest one on Android doesn't have this issue. The iOS side also works fine after updating; only thing that I needed to change are the FeatureFlags - there are some new ones.

I requested permission to make a pull request from our closed fork @saibotma

**Comment by mikegapinski** [comment]
@saibotma Just heard back; got the green light. I'll post the update in a pull request on behalf of my client: HappyByte GmbH

**Comment by rvharjinderbains** [comment]
@mikegapinski thank you

**Comment by gauravmehta13** [comment]
Hi @mikegapinski , in the meantime while the PR gets merged can you please share your git repo so that we can use it in the app?

**Comment by rvharjinderbains** [comment]
@mikegapinski Yes that would be really great if you share your repo as @gauravmehta13 mentioned.

**Comment by Gaurav-CareMonitor** [comment]
@mikegapinski  Any updates on the PR?

**Comment by Gaurav-CareMonitor** [comment]
@rvharjinderbains I have created a PR with updated SDK version 7.0.1 [here](https://github.com/saibotma/jitsi_meet_wrapper/pull/60) CC @saibotma 
If you want to use git version you can use it like below 

```
  jitsi_meet_wrapper:
    git:
      url: https://github.com/Gaurav-CareMonitor/jitsi_meet_wrapper.git
      ref: master
      path: jitsi_meet_wrapper/
 ```

**Comment by rvharjinderbains** [comment]
@Gaurav-CareMonitor Thank you. I will check and let you know If I face any issue.

**Comment by saibotma** [comment]
Thanks for your contributions. A new version will soon be released. I will thus close this issue.
