### ISSUE TITLE
On Target sdk version 31 or above app crashes on Android 12 release build

### ISSUE THREAD

**Issue by MusabBoltX** [saibotma/jitsi_meet_wrapper#63]
**### RELEASE LOGS:**

I/flutter ( 5491): JitsiMeetingOptions: JitsiMeetingOptions{roomNameOrUrl: jitsi-meet-wrapper-test-room, serverUrl: null, subject: My Plugin Test Meeting, token: , isAudioMuted: true, isAudioOnly: false, isVideoMuted: true, userDisplayName: Plugin Test User, userEmail: fake@email.com, userAvatarUrl: null, featureFlags: {}, configOverrides: null}

I/flutter ( 5491): onOpened

Result: App crashed

**Comment by saibotma** [comment]
Should be fixed with the upcoming version. I close this, but feel free to reopen, when the issue still appears.
