### ISSUE TITLE
add prejoinpage constants

### ISSUE THREAD

**Issue by Joseph-Nathan** [saibotma/jitsi_meet_wrapper#70]
add constants
```
export const PREJOIN_PAGE_ENABLED = 'prejoinpage.enabled';
```

**Comment by Me262a** [comment]
I also had to add it manually to the package
      case FeatureFlag.isPreJoinPageEnabled:
        return 'prejoinpage.enabled';

**Comment by isaanyoha** [comment]
> I also had to add it manually to the package case FeatureFlag.isPreJoinPageEnabled: return 'prejoinpage.enabled';

Did it work after what you did?

**Comment by saibotma** [comment]
I am sorry for answering late.
Feel free to create a PR implementing this feature.

**Comment by isaanyoha** [comment]
> I am sorry for answering late. Feel free to create a PR implementing this feature.

Not a problem, man
Ok, I will check how to do that. Thank you!

**Comment by saibotma** [comment]
Just ask here if you have any questions.

**Comment by saibotma** [comment]
This i now live in `0.1.2`.
