### ISSUE TITLE
Invalid notification (no valid small icon):

### ISSUE THREAD

**Issue by AbdouEsi** [saibotma/jitsi_meet_wrapper#76]
hi 

i have this issue when start a meeting : 

Invalid notification (no valid small icon):

E/JitsiMeetSDK(18365): java.lang.RuntimeException: Unable to start service org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService@6fb88f3 with Intent { cmp=com.maxenter/org.jitsi.meet.sdk.JitsiMeetOngoingConferenceService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=JitsiOngoingConferenceChannel pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 category=call actions=2 vis=PUBLIC)

**Comment by chetu-ko** [comment]
Error exists may be beacuase of notification icon. You may not added the notification icon in your andriod res folder.

https://github.com/jitsi/jitsi-meet/issues/11847    
Please go thtough this link here they have solved solution or please see the example folder of android/src/main/re.
