### ISSUE TITLE
update jitsi_meet_wrapper_platform_interface 

### ISSUE THREAD

**Issue by gilasraafi421** [saibotma/jitsi_meet_wrapper#78]
hello sir, can you update jitsi_meet_wrapper_platform_interface ?

enum FeatureFlag {
  /// Flag indicating if add-people functionality should be enabled.
  /// Default: enabled (true).
  isAddPeopleEnabled,

  /// Flag indicating if the SDK should not require the audio focus.
  /// Used by apps that do not use Jitsi audio.
  /// Default: disabled (false).
  isAudioFocusDisabled,

  /// Flag indicating if the audio mute button should be displayed.
  /// Default: enabled (true).
  isAudioMuteButtonEnabled,

  /// Flag indicating that the Audio only button in the overflow menu is enabled.
  /// Default: enabled (true).
  isAudioOnlyButtonEnabled,

  /// Flag indicating if calendar integration should be enabled.
  /// Default: enabled (true) on Android, auto-detected on iOS.
  isCalendarEnabled,

  /// Flag indicating if call integration (CallKit on iOS, ConnectionService on Android)
  /// should be enabled.
  /// Default: enabled (true).
  isCallIntegrationEnabled,

  //  Flag indicating if car mode should be enabled.
  //  Default: enabled (true).
  isCarModeEnabled,

  /// Flag indicating if close captions should be enabled.
  /// Default: enabled (true).
  isCloseCaptionsEnabled,

  /// Flag indicating if conference timer should be enabled.
  /// Default: enabled (true).
  isConferenceTimerEnabled,

  /// Flag indicating if chat should be enabled.
  /// Default: enabled (true).
  isChatEnabled,

  /// Flag indicating if the filmstrip should be enabled.
  /// Default: enabled (true).
  isFilmstripEnabled,

  /// Flag indicating if fullscreen (immersive) mode should be enabled.
  /// Default: enabled (true).
  isFullscreenEnabled,

  /// Flag indicating if the Help button should be enabled.
  /// Default: enabled (true).
  isHelpButtonEnabled,

  /// Flag indicating if invite functionality should be enabled.
  /// Default: enabled (true).
  isInviteEnabled,

  /// Flag indicating if recording should be enabled in iOS.
  /// Default: disabled (false).
  isIosRecordingEnabled,

  /// Flag indicating if screen sharing should be enabled in iOS.
  /// Default: disabled (false).
  isIosScreensharingEnabled,

  /// Flag indicating if screen sharing should be enabled in android.
  /// Default: enabled (true).
  isAndroidScreensharingEnabled,

  // Flag indicating if speaker statistics should be enabled.
  // Default: enabled (true).
  isSpeakerstatsEnabled,

  /// Flag indicating if kickout is enabled.
  /// Default: enabled (true).
  isKickoutEnabled,

  /// Flag indicating if live-streaming should be enabled.
  /// Default: auto-detected.
  isLiveStreamingEnabled,

  /// Flag indicating if lobby mode button should be enabled.
  /// Default: enabled.
  isLobbyModeEnabled,

  /// Flag indicating if displaying the meeting name should be enabled.
  /// Default: enabled (true).
  isMeetingNameEnabled,

  /// Flag indicating if the meeting password button should be enabled.
  /// Note that this flag just decides on the button, if a meeting has a password
  /// set, the password dialog will still show up.
  /// Default: enabled (true).
  isMeetingPasswordEnabled,

  /// Flag indicating if the notifications should be enabled.
  /// Default: enabled (true).
  isNotificationsEnabled,

  /// Flag indicating if the audio overflow menu button should be displayed.
  /// Default: enabled (true).
  isOverflowMenuEnabled,

  /// Flag indicating if Picture-in-Picture should be enabled.
  /// Default: auto-detected.
  isPipEnabled,

  // Flag indicating if Picture-in-Picture button should be shown while screen sharing.
  // Default: disabled (false).
  isPipWhileScreenSharingEnabled,

  // Flag indicating if the prejoin page should be enabled.
  // Default: enabled (true).
  isPrejoinPageEnabled,

  /// Flag indicating if raise hand feature should be enabled.
  /// Default: enabled.
  isRaiseHandEnabled,

  /// Flag indicating if the reactions feature should be enabled.
  /// Default: enabled (true).
  isReactionsEnabled,

  /// Flag indicating if recording should be enabled.
  /// Default: auto-detected.
  isRecordingEnabled,

  /// Flag indicating if the user should join the conference with the replaceParticipant functionality.
  /// Default: (false).
  isReplaceParticipant,

  /// Flag indicating the local and (maximum) remote video resolution. Overrides
  /// the server configuration.
  /// Default: (unset).
  resolution,

  /// Flag indicating if the security options button should be enabled.
  /// Default: enabled (true).
  isSecurityOptionsEnabled,

  /// Flag indicating if server URL change is enabled.
  /// Default: enabled (true).
  isServerUrlChangeEnabled,

  // Flag indicating if settings should be enabled.
  // Default: enabled (true).
  isSettingsEnabled,

  /// Flag indicating if tile view feature should be enabled.
  /// Default: enabled.
  isTileViewEnabled,

  /// Flag indicating if the toolbox should be always be visible
  /// Default: disabled (false).
  isToolboxAlwaysVisible,

  /// Flag indicating if the toolbox should be enabled
  /// Default: enabled.
  isToolboxEnabled,

  /// Flag indicating if the video mute button should be displayed.
  /// Default: enabled (true).
  isVideoMuteButtonEnabled,

  /// Flag indicating if the video share button should be enabled
  /// Default: enabled (true).
  isVideoShareButtonEnabled,

  /// Flag indicating if the welcome page should be enabled.
  /// Default: disabled (false).
  isWelcomePageEnabled,
}

String _toFeatureFlagString(FeatureFlag featureFlag) {
    switch (featureFlag) {
      case FeatureFlag.isAddPeopleEnabled:
        return 'add-people.enabled';
      case FeatureFlag.isAudioFocusDisabled:
        return 'audio-focus.disabled';
      case FeatureFlag.isAudioMuteButtonEnabled:
        return 'audio-mute.enabled';
      case FeatureFlag.isAudioOnlyButtonEnabled:
        return 'audio-only.enabled';
      case FeatureFlag.isCalendarEnabled:
        return 'calendar.enabled';
      case FeatureFlag.isCallIntegrationEnabled:
        return 'call-integration.enabled';
      case FeatureFlag.isCarModeEnabled:
        return 'car-mode.enabled';
      case FeatureFlag.isCloseCaptionsEnabled:
        return 'close-captions.enabled';
      case FeatureFlag.isConferenceTimerEnabled:
        return 'conference-timer.enabled';
      case FeatureFlag.isChatEnabled:
        return 'chat.enabled';
      case FeatureFlag.isFilmstripEnabled:
        return 'filmstrip.enabled';
      case FeatureFlag.isFullscreenEnabled:
        return 'fullscreen.enabled';
      case FeatureFlag.isHelpButtonEnabled:
        return 'help.enabled';
      case FeatureFlag.isInviteEnabled:
        return 'invite.enabled';
      case FeatureFlag.isIosRecordingEnabled:
        return 'ios.recording.enabled';
      case FeatureFlag.isIosScreensharingEnabled:
        return 'ios.screensharing.enabled';
      case FeatureFlag.isAndroidScreensharingEnabled:
        return 'android.screensharing.enabled';
      case FeatureFlag.isSpeakerstatsEnabled:
        return 'speakerstats.enabled';
      case FeatureFlag.isKickoutEnabled:
        return 'kick-out.enabled';
      case FeatureFlag.isLiveStreamingEnabled:
        return 'live-streaming.enabled';
      case FeatureFlag.isLobbyModeEnabled:
        return 'lobby-mode.enabled';
      case FeatureFlag.isMeetingNameEnabled:
        return 'meeting-name.enabled';
      case FeatureFlag.isMeetingPasswordEnabled:
        return 'meeting-password.enabled';
      case FeatureFlag.isNotificationsEnabled:
        return 'notifications.enabled';
      case FeatureFlag.isOverflowMenuEnabled:
        return 'overflow-menu.enabled';
      case FeatureFlag.isPipEnabled:
        return 'pip.enabled';
      case FeatureFlag.isPipWhileScreenSharingEnabled:
        return 'pip-while-screen-sharing.enabled';
      case FeatureFlag.isPrejoinPageEnabled:
        return 'prejoinpage.enabled';
      case FeatureFlag.isRaiseHandEnabled:
        return 'raise-hand.enabled';
      case FeatureFlag.isReactionsEnabled:
        return 'reactions.enabled';
      case FeatureFlag.isRecordingEnabled:
        return 'recording.enabled';
      case FeatureFlag.isReplaceParticipant:
        return 'replace.participant';
      case FeatureFlag.resolution:
        return 'resolution';
      case FeatureFlag.isSecurityOptionsEnabled:
        return 'security-options.enabled';
      case FeatureFlag.isServerUrlChangeEnabled:
        return 'server-url-change.enabled';
      case FeatureFlag.isSettingsEnabled:
        return 'settings.enabled';
      case FeatureFlag.isTileViewEnabled:
        return 'tile-view.enabled';
      case FeatureFlag.isToolboxAlwaysVisible:
        return 'toolbox.alwaysVisible';
      case FeatureFlag.isToolboxEnabled:
        return 'toolbox.enabled';
      case FeatureFlag.isVideoMuteButtonEnabled:
        return 'video-mute.enabled';
      case FeatureFlag.isVideoShareButtonEnabled:
        return 'video-share.enabled';
      case FeatureFlag.isWelcomePageEnabled:
        return 'welcomepage.enabled';
    }
  }

**Comment by saibotma** [comment]
Hey there,

please create a PR with your update ideas. Thanks!

**Comment by saibotma** [comment]
The `FeatureFlag` enum got removed in `0.2.0`. Have a look at the [changelog](https://pub.dev/packages/jitsi_meet_wrapper/changelog#020) for more information, please.
This should resolve your issue.
