### ISSUE TITLE
Android app fail with error Could not resolve org.jitsi.react:jitsi-meet-sdk:7.0.1.

### ISSUE THREAD

**Issue by jigar541patel** [saibotma/jitsi_meet_wrapper#79]
Hello. running in android getting error 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:7.0.1.
     Required by:
         project :app > project :jitsi_meet_wrapper
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:7.0.1.
         > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/7.0.1/jitsi-meet-sdk-7.0.1.pom'.
            > Could not GET 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/7.0.1/jitsi-meet-sdk-7.0.1.pom'. Received status code 401 from server: Unauthorized

![Screenshot 2023-02-17 at 8 32 42 PM](https://user-images.githubusercontent.com/42966795/219690638-6d980d53-5193-4ee2-8992-1c9179d6d725.png)

**Comment by purvghori** [comment]
Same error occurred

<img width="1113" alt="Screenshot 2023-02-18 at 8 52 50 PM" src="https://user-images.githubusercontent.com/76478074/219873854-77d7a8bc-40ad-4476-a97e-60e40c653466.png">

**Comment by chetu-ko** [comment]
This error may be due to an unsupported Gradle version. As per the Jitsi SDK 7+ it uses Gradle version 7.4. Please update your Gradle version probably error may go.

**Comment by purvghori** [comment]
@chetu-ko  Thanks for the reply 

I update gradle version 7.4 but still getting this Error

**Comment by chetu-ko** [comment]
Can you please provide the Gradle version?

**Comment by purvghori** [comment]
Here is my gradle version

<img width="1117" alt="Screenshot 2023-02-19 at 9 30 05 PM" src="https://user-images.githubusercontent.com/76478074/219959557-de562c69-462b-42e6-962d-d1ce85bf8e62.png">

**Comment by chetu-ko** [comment]
have you also changed your classpath value in android/gradle path.

classpath "com.android.tools.build:gradle:7.0.1"

**Comment by purvghori** [comment]
@chetu-ko  Thanks for the help 

The app is installed but one more issue with video's black screen  #68 

if you know anything about this issue please help me

**Comment by jigar541patel** [comment]
Hi @purvghori are you able to run app now ? can you share you share me your gradle-wrapper.properties , app/build.gradle ,android/build.gradle and settings.gradle file .becz after changing to @chetu-ko i am still same facing issue

**Comment by purvghori** [comment]
@jigar541patel 

1. Update your gradle-wrapper.properties file => distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
2. Updare your  android/Gradle.build file => classpath "com.android.tools.build:gradle:7.0.1"

if you use proguard then remove this line => useProduard true 

<img width="851" alt="Screenshot 2023-02-20 at 8 43 36 PM" src="https://user-images.githubusercontent.com/76478074/220143497-360ea28b-b0a1-46be-b5eb-bc78f562776a.png">

**Comment by jigar541patel** [comment]
@purvghori and @chetu-ko I have removed this and changed to distribution url 7.4 and gradle build 7.0.1 but still getting same error 
![Screenshot 2023-02-21 at 4 49 43 PM](https://user-images.githubusercontent.com/42966795/220331689-01cd66fe-c967-4d41-bf31-f63987d5635b.png)
![Screenshot 2023-02-21 at 4 49 26 PM](https://user-images.githubusercontent.com/42966795/220331715-714f9775-7cc3-42f9-bd9f-cd8b550266a9.png)
![Screenshot 2023-02-21 at 4 49 08 PM](https://user-images.githubusercontent.com/42966795/220331727-7b3d121b-7848-48c3-958b-58a40f66affc.png)

**Comment by chetu-ko** [comment]
@jigar541patel  Did you try running flutter clean after changing the settings?

**Comment by jigar541patel** [comment]
@chetu-ko yes i tried cleaning but issue still persist.

**Comment by ccs1428** [comment]
last 2 days i am in the same issue, any body able to resolve it. @chetu-ko @jigar541patel

**Comment by jigar541patel** [comment]
issue is with android studio by version updating to Android Studio Electric Eel | 2022.1.1 Patch 2 will work.please try @ccs1428 @chetu-ko @purvghori
