### ISSUE TITLE
Audio and Video of participants are always on mute in the latest version 0.0.6

### ISSUE THREAD

**Issue by neerajapex** [saibotma/jitsi_meet_wrapper#85]
Hi,
    I am using the latest version of **jitsi_meet_wrapper** and **flutter** versions. If I join the meeting through the browser everything is working fine but If I join through the flutter app, my audio/video is always muted for other participants and their audio/video is also muted in my app even If it's unmuted from their side.

     If I use the older version of '**jitsi_meet_wrapper (0.0.5)**' It's working almost as expected. Except one problem I am facing in the older version is If I join the conference first and later the other participants joins with muted video then I can't see the other participant's video after they unmute themself also but the audio is working fine. 
If someone joins the conference with unmuted video from the browser and later I join then everything is working fine. 
    For the last week, I am trying to make Jitsi work in my flutter app. Now everything is working fine with the '**jitsi_meet_wrapper (0.0.5)**' except above-mentioned issue.

I tried this solution which helped me to resolve a few problems.
https://github.com/saibotma/jitsi_meet_wrapper/issues/33

Please suggest to me how can I solve the problem either in jitsi_meet_wrapper version 0.0.6 or 0.0.5. I have tried most of the solutions I could find on the internet.

**Comment by saibotma** [comment]
Hey there,

please try the newest version and create a fully reproducible example if it still does not work.

**Comment by altabmw01** [comment]
Hello, Did you get a solution? I also have an audio problem with my app. I am using jitsi_meet_wrapper: ^0.2.0+1 and not getting audio. I can press on the mike and it's unmuted but no sound is delivered to others. Even I can't hear anyone.
