### ISSUE TITLE
New meeting started but then closed immediately with the old meeting when click on the notification on status bar

### ISSUE THREAD

**Issue by coderof19clc7** [saibotma/jitsi_meet_wrapper#87]
@saibotma, I have an issue is that after starting a call, I saw that there is a notification with the title "Ongoing meeting" and body "You are currently in a meeting. Tap to return to it."
When tap the notification, no matter i'm in foreground or background, a new call will start while the old one still running and the result is both 2 call closed automatically.
What should I do to fix that ?

Below is the error I got after tapping on the notification
`D/OrientationModule( 5340): onActivitySaveInstanceState
E/JitsiMeetSDK( 5340): Error running onHostPause, ignoring
E/JitsiMeetSDK( 5340): java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetWrapperActivity Paused activity: JitsiMeetWrapperActivity
E/JitsiMeetSDK( 5340): 	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:88)
E/JitsiMeetSDK( 5340): 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:603)
E/JitsiMeetSDK( 5340): 	at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:120)
E/JitsiMeetSDK( 5340): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onStop(JitsiMeetActivity.java:120)
E/JitsiMeetSDK( 5340): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
E/JitsiMeetSDK( 5340): 	at android.app.Activity.performStop(Activity.java:7181)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4291)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4343)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread.-wrap28(ActivityThread.java)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
E/JitsiMeetSDK( 5340): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/JitsiMeetSDK( 5340): 	at android.os.Looper.loop(Looper.java:154)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/JitsiMeetSDK( 5340): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 5340): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
E/JitsiMeetSDK( 5340): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
E/JitsiMeetSDK( 5340): 
E/JitsiMeetSDK( 5340): java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetWrapperActivity Paused activity: JitsiMeetWrapperActivity
E/JitsiMeetSDK( 5340): 	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:88)
E/JitsiMeetSDK( 5340): 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:603)
E/JitsiMeetSDK( 5340): 	at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:120)
E/JitsiMeetSDK( 5340): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onStop(JitsiMeetActivity.java:120)
E/JitsiMeetSDK( 5340): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
E/JitsiMeetSDK( 5340): 	at android.app.Activity.performStop(Activity.java:7181)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4291)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4343)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread.-wrap28(ActivityThread.java)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
E/JitsiMeetSDK( 5340): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/JitsiMeetSDK( 5340): 	at android.os.Looper.loop(Looper.java:154)
E/JitsiMeetSDK( 5340): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/JitsiMeetSDK( 5340): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 5340): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
E/JitsiMeetSDK( 5340): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
D/OrientationModule( 5340): onActivityStopped
`

**Comment by saibotma** [comment]
Hey there,

maybe those help:
- #14 
- #76

**Comment by saibotma** [comment]
Fixed with version 0.2.0.
