### ISSUE TITLE
Flutter app closes when joining meeting

### ISSUE THREAD

**Issue by ndizihiwesimon** [saibotma/jitsi_meet_wrapper#90]
I have defined pro-guard.pro and all other necessary configurations as required, but app crashes when joining meeting with the following message in console:

`E/JitsiMeetSDK(15580): 	... 9 more
I/JitsiMeetSDK(15580): JitsiConnectionService onAbort 47215E8C-B82C-4DA9-9D93-A99886DDAAA4
D/JitsiMeetSDK(15580): JitsiConnectionService onStateChanged: DISCONNECTED 47215E8C-B82C-4DA9-9D93-A99886DDAAA4
I/Process (15580): Sending signal. PID: 15580 SIG: 9
Lost connection to device.`

**Comment by Aravin** [comment]
Same error for me!

**Comment by ndizihiwesimon** [comment]
I have been able to resolve the error:

I have come across a solution:

 1. Open your `project>android` using android studio (Select android folder underneath the project name) wait for build to finish.
 2. `android>res` right click on res folder in android project and choose image asset from new section
 3. Create icon with following config  
   `Name`: ic_notification  
   `Icon Type`: Notification Icons

Issue will be resolved.

**Comment by Aravin** [comment]
No, its still crashing the app.
