### ISSUE TITLE
Feature Request: unwrap pip window programmatically

### ISSUE THREAD

**Issue by shabanov-krl** [saibotma/jitsi_meet_wrapper#93]
when meeting in progress and in pip, i want to show `open meeting` button for user in flutter

right now i can only call `joinMeeting` method on tap button, but it will cause re-joining instead of unwraping pip

**Comment by saibotma** [comment]
Hey there,

I could not find anything that would solve your issue in the official documentation.
You can however create an issue [here](https://github.com/jitsi/jitsi-meet).
