### ISSUE TITLE
[IOS] Call ends immediately after joining

### ISSUE THREAD

**Issue by TetrixGauss** [saibotma/jitsi_meet_wrapper#97]
Hello all!

I have implemented the package and everything works fine in android. 
On iOS i can init the jitsi view and when i am tapping the Join Meeting button, the screen seems to be loading but after 1 second it ends the call! I have no crash errors and from the other side of the call i can see the user join and leave as soon as it connects to the call.

Any ideas?

Thank you in advance!

**Comment by TetrixGauss** [comment]
Nevermind!

The problem was that i was trying to run it on a iOS emulator!  It runs well on physical device!!

On android emulator runs though!

**Comment by ndizihiwesimon** [comment]
Have you deployed it on play store? if yes, how did you deal with the issue of call being dropped as soon as a user joins the meeting?
