### ISSUE TITLE
Join Meeting Screen 

### ISSUE THREAD

**Issue by yashthakkar16** [saibotma/jitsi_meet_wrapper#98]
When we use JitsiMeetWrapper. joinmeeting method takes us to some Join meeting Screen where we can manipulate our audio video and name; it also contains a button named Join Meeting.
My question is how to change the screen name and button name of that screen in Flutter, for instance, how we can change joining meet to connect meet or something else?

**Comment by saibotma** [comment]
Hey there,

this package is a wrapper around the official JitsiMeet SDKs. You can have a look at the official documentations (https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk and https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk) and try finding a feature flag that does this for you. However, i assume that it is not possible.
